name: Deploy Nodejs Application to Hostinger

on:
  push: 
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.201.88.86
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /var/www/html/node_ec2
            git pull
            docker compose up -d --build


